name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

defaults:
  run:
    working-directory: ./actions/bundle-plugin/

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Install node
        uses: actions/setup-node@v3
        with:
            node-version-file: /actions/bundle-plugin/.node-version

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
            cache-dependency-path: ./actions/bundle-plugin/package-lock.json
            cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: yarn npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test